BoardList/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='BoardList'
urlpatterns = [
    path('', views.BoardListLoad ,name='BoardListLoad' ),
    path('viewdata/<int:id>/', views.viewdata1, name="viewdata"),
    path('Itemdelete/<int:id>/', views.Itemdelete, name="Itemdelete"),
    path('ItemSave/', views.ItemSave, name="ItemSave"),
    path('writeboard/', include('WriteBoard.urls'), name="WriteBoard"),
    path('logout', views.logout, name="logout"),
]

Config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('Default.urls')),
]

Default/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.DefaultLoad ,name='DefaultLoad' ),
    path('MemberJoin/', include('MemberJoin.urls'),name='MemberJoin'),
    path('LoginClick/', views.LoginClick,name='LoginClick'),
    path('List/', include('BoardList.urls'),name='BoardList'),
]

WriteBoard/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.writeboard1, name="SelectBoard"),
    path('Board_Insert/', views.Board_Insert, name="Board_Insert"),
]

BoardList/models.py
from django.db import models

# Create your models here.

Default/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Board(models.Model):
    boardno = models.AutoField(db_column='boardNo', primary_key=True)  # Field name made lowercase.
    boardtitle = models.CharField(db_column='boardTitle', max_length=300)  # Field name made lowercase.
    boardcontent = models.CharField(db_column='boardContent', max_length=2000)  # Field name made lowercase.
    mid = models.CharField(db_column='mId', max_length=50)  # Field name made lowercase.
    boarddate = models.DateTimeField(db_column='boardDate')  # Field name made lowercase.
    boardcount = models.DecimalField(db_column='boardCount', max_digits=10, decimal_places=0)  # Field name made lowercase.
    last_dt = models.DateTimeField(db_column='LAST_DT', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Board'


class Smember(models.Model):
    mid = models.CharField(db_column='mID', primary_key=True, max_length=100)  # Field name made lowercase.
    mname = models.CharField(db_column='mName', max_length=100, blank=True, null=True)  # Field name made lowercase.
    mmode = models.CharField(db_column='mMode', max_length=1, blank=True, null=True)  # Field name made lowercase.
    mpw = models.CharField(db_column='mPW', max_length=50, blank=True, null=True)  # Field name made lowercase.
    malias = models.CharField(db_column='mAlias', max_length=100, blank=True, null=True)  # Field name made lowercase.
    mbirth = models.CharField(db_column='mBirth', max_length=20, blank=True, null=True)  # Field name made lowercase.
    mzip_cd = models.CharField(db_column='mZIP_CD', max_length=6, blank=True, null=True)  # Field name made lowercase.
    maddr = models.CharField(db_column='mADDR', max_length=100, blank=True, null=True)  # Field name made lowercase.
    mdetl_addr = models.CharField(db_column='mDETL_ADDR', max_length=100, blank=True, null=True)  # Field name made lowercase.
    mphone = models.CharField(db_column='mPHONE', max_length=15, blank=True, null=True)  # Field name made lowercase.
    memail = models.CharField(db_column='mEMAIL', max_length=50, blank=True, null=True)  # Field name made lowercase.
    mmemo = models.CharField(db_column='mMEMO', max_length=1000, blank=True, null=True)  # Field name made lowercase.
    inst_dt = models.DateTimeField(db_column='INST_DT', blank=True, null=True)  # Field name made lowercase.
    last_dt = models.DateTimeField(db_column='LAST_DT', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'sMember'

WriteBoard/models.py
from django.db import models

# Create your models here.

BoardList/views.py
from django.shortcuts import render, redirect
from Default.models import Board
from Default.models import Smember
from django.views.decorators.csrf import csrf_exempt
from django.db import connections
from django.http import HttpResponse
import datetime
# Create your views here.
def BoardListLoad(request):
    BoardList = Board.objects.all().order_by('boardno')
    print(BoardList)
    if (request.session['myID'] == None):
        return redirect('/')
    iID = request.session['myID']
    print(request.session['myID'])
    myResult = Smember.objects.filter(mid=iID)
    context = {
        "BoardList": BoardList,
        "Member": myResult
    }
    return render(request, "BoardList.html", context)
# return render(request,"BoardList.html",{'BoardList': BoardList})


def viewdata1(request, id):
    if (request.session['myID'] == None):
        return redirect('/')

    try:
        with connections['default'].cursor() as cursor:
            SQL = " Update  Board Set BoardCount = BoardCount " + " + 1 "
            SQL += " Where BoardNo=" + str(id)
            cursor.execute(SQL)

    except Exception as ex:
        print(' Error가 발생 했습니다', ex)
        return render(request, "BoardList.html")

    BoardData = Board.objects.all().get(boardno=id)

    context = {
        "BoardData": BoardData,
        "sID": request.session['myID']
    }
    return render(request, "ViewData.html", context)


def Itemdelete(request, id):
    if (id == None):
        return redirect('/List')

    Board.objects.filter(boardno=id).delete()
    return redirect('/List')


@csrf_exempt
def ItemSave(request):
    sNum = request.POST['iNum']
    sboardTitle = request.POST['iTitle']
    sboardContent = request.POST['iContent']

    iID = request.session['myID']
    now = datetime.datetime.now()
    if iID != None:
        try:
            with connections['default'].cursor() as cursor:
                SQL = " Update  Board Set BoardTitle='" + sboardTitle + "' , BoardContent='" + sboardContent + "' "
                SQL += " , Last_DT=getdate() "
                SQL += " Where BoardNo=" + sNum
                cursor.execute(SQL)
        except Exception as ex:
            print('저장에서 Error가 발생 했습니다', ex)
            return render(request, "List/List.html")
    # return response({"success": False, "msg": "에러입니다."})

    print(' 업데이트가 정상저장 되었습니다')
    return redirect('/List')
    # return HttpResponse(sNum)


def logout(request):
    request.session['myID'] = None
    return redirect('/')

Default/views.py
from django.shortcuts import render , redirect
from django.views.decorators.csrf import csrf_exempt
from Default.models import Smember
from django.contrib.auth import authenticate, login
from django.http import JsonResponse
import json

# Create your views here.

def DefaultLoad(request):
    return render(request,'Default.html')

@csrf_exempt
def LoginClick(request):
    # POST 요청일 때

    jsonObject = json.loads(request.body.decode('utf-8'))
    iID=jsonObject['sID']
    iPW=jsonObject['sPW']

    try:
        myResult = Smember.objects.filter(mid=iID, mpw=iPW).count()
    except Exception as ex:
        print('에러가 발생 했습니다', ex)

    if(myResult==1):
        request.session['myID'] = iID  # ☆ 세션 등록 ☆
        # return render(request, "Default.html", context)

        return JsonResponse({'msg':'Success'})
    else:
        return JsonResponse({'msg':'Fail'})

WriteBoard/views.py
from django.shortcuts import render, redirect
from Default.models import Board
from Default.models import Smember
from django.views.decorators.csrf import csrf_exempt
from django.db import connections
from django.http import HttpResponse
import datetime

# Create your views here.

def writeboard1(request):
    print("List_WriteBoard:")
    #BoardData = Board.objects.all().get(boardno=id)
    context={ 'myID': request.session['myID'] }
    return render(request, "WriteBoard.html",context)



@csrf_exempt
def Board_Insert(request):

    sboardTitle = request.POST['iTitle']
    sboardContent = request.POST['iContent']
    iID=request.session['myID']
    now = datetime.datetime.now()
    if iID != "":
        try:
            rows = Board.objects.create(boardtitle=sboardTitle, boardcontent=sboardContent, mid=iID, boarddate=now ,boardcount=0)
        except Exception as ex:
            print('저장에서 Error가 발생 했습니다', ex)
            return redirect("/List")

    print('게시판글쓰기가 정상저장 했습니다')
    #return render(request, "List/List.html")
    return redirect("/List")

templates/Default.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SIMPLE-BOARD - Login</title>
    <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
   <link href="{% static '/js/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="{% static '/css/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="{% static '/css/sb-admin-2.min.css' %}" rel="stylesheet">

 <script type="text/javascript">
        $(document).ready(function () {

            $('#sID').on('keypress', function (event) {
                if (event.which == '13') {
                    $('#sPW').select();
                    return false;
                }
            });

            $('#btnSubmit').on('click', function (e) {

                if ($.trim($('#sID').val()) == "") {
                    alert('아이디를 입력하세요!');
                    return false;
                }

                if ($.trim($('#sPW').val()) == "") {
                    alert('PASSWORD  입력하세요!');
                    return false;
                }

                var param = {'sID' : $.trim($('#sID').val()) , 'sPW' : $.trim($('#sPW').val()) };

                $.ajax({
                    type: 'post',
                    url:'LoginClick/',
                    contentType:"application/json; charset=utf-8",
                    dataType:"json",
                    header:{
                        'X-CSRFTOKEN' : '{{ csrf_token }}'
                    },
                    timeout:0,
                    async:true,
                    data: JSON.stringify(param),
                    success: function (json) {
                        console.log("data pass success", json);
                        console.log("data pass success", json.msg);
                        if(json.msg=='Success'){

                            //location.href = "http://127.0.0.1:9007/List/";
                            location.href = './List/';
                        }else{
                            alert('ID,PW가 일치하지않습니다.');
                        }

                    },
                    error: function (xhr, errmsg, err) {
                        console.log('Error');
                    }

                });
                return false;
            });
            $('#sID').select();
        });

    </script>

</head>

<body class="bg-gradient-primary">
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome dJango!</h1>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                id="sID" aria-describedby="emailHelp" value="k12345"
                                                placeholder="Enter Your ID">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="sPW" placeholder="Enter Password" value="123">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">Remember Me</label>
                                            </div>
                                        </div>
                                        <input type="submit" id="btnSubmit" class="btn btn-primary btn-user btn-block" value="Login" >
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                         <a class="small" href="MemberJoin">Create an Account</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'css/vendor/jquery/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static '/js/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static  '/js/sb-admin-2.min.js' %}"></script>

</body>

</html>

templates/ViewData.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static '/css/default.css' %}" type="text/css" rel="stylesheet"/>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.9.0/jquery.js"></script>
    <style>
        th, td {
            padding: 10px 15px;
        }
        .grid {
            width: 650px;
            margin: 50px auto;
            background-color: white;
            text-align: center;
        }
        .grid2 {
            display: flex;
            width: 220px;
            margin: 10px auto;
            background-color: white;
            text-align: center;
        }
         .grid3 {
            display: flex;
            width: 70px;
            margin: 10px auto;
            background-color: white;
            text-align: center;
        }
    </style>

    <script type="text/javascript">
        window.onload = function () {
            let tempID = '{{ sID }}';
            let tempID2 = '{{ BoardData.mid }}';

            if (tempID == tempID2) {
                $('#div2').show();
                $('#div1').hide();
            }else{
                $('#div1').show();
                $('#div2').hide();
            }
        }

        function Previous() {
            //location.href = "./../../";
            location.href = '{% url 'BoardList:BoardListLoad' %}';
        }

        function ItemSave() {
            let msg='저장하시겠습니까?';
            let result = confirm(msg);
            if(!result){
                return false;
            }

            var form = document.getElementById("form1");

            form.action = "./../../ItemSave/";
            form.mothod = "post";
            form.submit();
        }

        function ItemDelete() {
            let msg='삭제 하시겠습니까?';
            let result = confirm(msg);
            if(!result){
                return false;
            }
            location.href = "./../../Itemdelete/{{ BoardData.boardno }}";
        }

    </script>
</head>
<body>
<div class="grid" style="background-color: white">
    <form id="form1" action="" method="post" >

        <table class="tbs1" cellspacing="0" cellpadding="0" width="100%" border="0">
             <tr>
                <th style="width:300px;">
                    &nbsp;&nbsp;<b>조횟수</b></th>
                <td style="width:500px;"><input type="text" name="iCount" id="iCount" style="text-align: center;width:400px;height:30px;padding:5px;" value="{{ BoardData.boardcount }}" ></td>
            </tr>
            <tr>
                <th style="width:300px;">
                    &nbsp;&nbsp;<b>boardNo</b></th>
                <td style="width:500px;"><input type="text" name="iNum" id="iNum" style="text-align: center;width:400px;height:30px;padding:5px;" value="{{ BoardData.boardno }}" ></td>
            </tr>
            <tr>
                <th>
                    &nbsp;&nbsp;<b>boardTitle(제목)</b></th>
                <td><input type="text" style="text-align: center;width:400px;height:30px;padding:5px;" class="input-form" name="iTitle"  value="{{ BoardData.boardtitle }}"></td>
            </tr>
            <tr>
                <th>
                    &nbsp;&nbsp;<b>작성자</b></th>
                <td><input type="text" name="iID" style="text-align: center;width:400px;height:30px;padding:5px;" readonly="readonly" class="input-form"
                                 value="{{ BoardData.mid }} "></td>
            </tr>
            <tr>
                <th>
                    &nbsp;&nbsp;<b>내용 </b></th>
                <td><textarea type="text" name="iContent" style="text-align:left;width:400px;height:200px;padding:5px;" W class="input-form">{{ BoardData.boardcontent}}</textarea></td>
            </tr>
            <tr>
                <th>
                    &nbsp;&nbsp;<b>저장일 </b></th>
                <td><input type="text" style="text-align: center;width:400px;height:30px;padding:5px;" class="input-form"
                                 readonly="readonly" value="{{ BoardData.boarddate|date:'Y-m-d H:i' }}"></td>
            </tr>
        </table>
    </form>
    <div id="div1" class="grid3">
        <img src="{% static '/img/previous.png' %}" style="cursor:pointer" onclick="return Previous();" alt="">
    </div>
    <div id="div2" class="grid2" style="display:none">
        <img src="{% static '/img/previous.png' %}" style="cursor:pointer" onclick="return Previous();" alt="">&nbsp;&nbsp;
        <img src="{% static '/img/diskette_save.png' %}" id="imgSave"  onclick="return ItemSave();" style="cursor:pointer;" alt="">&nbsp;&nbsp;
        <img src="{% static '/img/trash.png' %}"  id="imgDelete" onclick="return ItemDelete();"   style="cursor:pointer;" alt="">
    </div>
</div>
</body>
</html>

templates/WriteBoard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   <title> 글쓰기 </title>
    <link href="{% static '/css/default.css' %}" type="text/css" rel="stylesheet"/>
    <style>

        .grid {
            width: 800px;
            margin: 50px auto;
            background-color: white;
            text-align: center;
        }
    </style>
    <script scr="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
    <script type="application/javascript">

        $(document).ready(function () {
            let sID = '{{ myID }}';
            $('#iID').val(sID);
        });

        function GoFirst() {
            location.href = './List/';
        }

        function preSend() {
            if ($.trim($('#iTitle').val()) == '') {
                alert('제목을 입력하세요.');
                return false;
            }

            if ($.trim($('#iContent').val()) == '') {
                alert('내용을 입력하세요.');
                return false;
            }

            var msg = '당신이 쓴글을 등록하시겠습니까?';
            var result = confirm(msg);

            if (!result) {
                return false;
            }

            var form = document.getElementById("form1");

            form.action = "./Board_Insert/";
            // form.mothod = "post";
            form.submit();
            return false;
        }
    </script>
</head>
<body>
<h1>게시판쓰기 입니다.</h1>

<div class="grid"><h1>글쓰기</h1></div>
<div class="black-box">
    <div class="white-box">
        <form  id="form1"  method="post" >
            <div class="grid">
                <table border="0" cellpadding="0" cellspacing="0" class="condition" style="width:100%;">
                    <tr>
                        <th>아이디</th>
                        <td><input type="text" id="iID" name="iID" placeholder="myID" readonly="readonly" class="input-form" style="width:90%;"
                                   value=""></td>
                    </tr>
                    <tr>
                        <th>제목</th>
                        <td><input type="text" id="iTitle" name="iTitle" placeholder="Title" class="input-form" style="width:90%;"
                                   value=""></td>
                    </tr>
                    <tr>
                        <th>글내용</th>
                        <td>  <textarea name="iContent" class="input-form" id="iContent"   style="text-align:left;width:90%;height:300px;padding:5px;" ></textarea></td>
                    </tr>
                    <tr>
                        <th></th>
                        <td>
                             <button type="button" class="send-btn" onclick="return GoFirst();">to_List</button>
                             <button type="submit" class="send-btn" onclick="return preSend();">Save</button>
                        </td>
                    </tr>
                </table>

            </div>
        </form>
    </div>
</div>
</body>
</html>